In [1]:
import pandas as pd

In [2]:
s=pd.Series([71,84,56,23,56,98,56])

In [3]:
type(s)

pandas.core.series.Series

In [4]:
print(s)

0    71
1    84
2    56
3    23
4    56
5    98
6    56
dtype: int64

In [5]:
s2=pd.Series([71,84,56,23,56,98,56],index=["A","B","C","D","E","F","G"])

In [6]:
print(s)

0    71
1    84
2    56
3    23
4    56
5    98
6    56
dtype: int64

In [7]:
s2

A    71
B    84
C    56
D    23
E    56
F    98
G    56
dtype: int64

In [8]:
data = {
    "Name": ["Piyush", "Rahul", "Aman", "Neha", "Priya"],
    "Age": [21, 22, 20, 23, 21],
    "City": ["Delhi", "Mumbai", "Noida", "Pune", "Jaipur"],
    "Marks": [85, 92, 78, 88, 95]
}


pd.DataFrame(data)

     Name  Age    City  Marks
0  Piyush   21   Delhi     85
1   Rahul   22  Mumbai     92
2    Aman   20   Noida     78
3    Neha   23    Pune     88
4   Priya   21  Jaipur     95

In [9]:
df=pd.DataFrame(data)

In [10]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

In [12]:
data=[['harry',34],['jack',67],['jacob',67],['shubham',67]]

In [13]:
data

[['harry', 34], ['jack', 67], ['jacob', 67], ['shubham', 67]]

In [14]:
pd.DataFrame(data,columns=["name","marks"])

      name  marks
0    harry     34
1     jack     67
2    jacob     67
3  shubham     67

In [15]:
data={"a":[4,6,3],"b":[56,34,343]}

In [16]:
df=pd.DataFrame(data)

In [17]:
df

   a    b
0  4   56
1  6   34
2  3  343

In [18]:
import numpy as np
arr=np.array([[1,2],[5,6]])

In [19]:
df=pd.DataFrame(arr,columns=["A","B"])

In [20]:
df

   A  B
0  1  2
1  5  6

In [21]:
data=pd.read_excel("data.xlsx")

In [22]:
data

       name  school  marks
0  shubham      sps     34
1    joshua     ups     45
2      jack     wps     45
3      alex     uis     67
4   jasmine     rts     45
5     rohan     rry     88
6     rishi  luxury     77
7    aakash     bbl     90

In [23]:
df=pd.read_csv("iris.csv")

In [24]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica


EDA(EXPOLATORY DATA SERVICE)

In [25]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [26]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [28]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [30]:
data=pd.read_csv("actor.json")

FileNotFoundError: [Errno 2] No such file or directory: 'actor.json'